#!/bin/sh
# vim:ft=sh:
# abstract: list albums by artist and show record label, helper for
# https://www.japh.se/2021/05/23/custom-beet-path-rules-for-record-labels.html
beet ls "$@"  -f '·$label· $path' \
  | sort -u                       \
  | perl -pe 's/·//g'
