#!/usr/bin/env sh
source /etc/profile
rofi \
        -modi drun \
        -show drun \
        -show-icons \
        -drun-match-fields name \
        -display-drun '~>' \
        -theme run \
        || rofi -show run \
        || dmenu_run
